#!/bin/sh

usage="aggregate_xml path_to_dir > output.xml"
descr="Aggregate xml files into single output xml with records"

. `dirname $0`/setup

for f in $1/*.edien.xml

do

	cat $f |
	lxinline -sw 'parts/part[1]/@sw' -ew 'parts/part[last()]/@ew'

done |
( echo '<records>' ; cat - ; echo '</records>') |
lxreplace -q "ent[@type~'^neg']" -t "<ent neg='yes'>&attrs;<xsl:attribute name='type'><xsl:value-of select='substring(@type,5)'/></xsl:attribute>&children;</ent>" |
lxreplace -q "ent[@type~'^loc']" -t "<ent>&attrs;<xsl:attribute name='type'>mod</xsl:attribute><xsl:attribute name='sloc'><xsl:value-of select='substring(@type,5)'/></xsl:attribute>&children;</ent>" |
lxreplace -q "ent[@type~'^time']" -t "<ent>&attrs;<xsl:attribute name='type'>mod</xsl:attribute><xsl:attribute name='stime'><xsl:value-of select='substring(@type,6)'/></xsl:attribute>&children;</ent>"
