#!/bin/sh

usage="prepare-scan <input.xml >output.xml"
descr="Convert XML resulting from excel conversion to pipeline input format."

. `dirname $0`/setup

while [ $# -gt 0 ]; do
  arg=$1
  shift
  case $arg in
    -d)
      docdate=$1
      shift
      ;;
    *)
      echo "usage: $usage" >&2
      exit 2
  esac
done

lib=$here/lib/prepare

cat > $tmp-in

cat $tmp-in |
lxt -s $lib/ltgformat.xsl |
lxaddids -e document -p "''" -f "%s%.04d" |
lxtransduce -q text $lib/paras.gr

